[env]
term = "xterm-256color"

[window]

opacity = 1.0

padding = { x = 3, y = 3 }

decorations = "None"
decorations_theme_variant = "Dark" # "Dark"

[font]

normal.family       = "Jetbrains Mono NerdFont"
bold.family         = "Jetbrains Mono NerdFont"
italic.family       = "Jetbrains Mono NerdFont"
bold_italic.family  = "Jetbrains Mono NerdFont"

size = 12.0
