xrdb $XDG_CONFIG_HOME/x11/xresources
xwallpaper --zoom /home/bkyle/.config/wall2.jpeg
xrandr --output eDP-1 --mode 2880x1920 --rate 120.00
xset r rate 250
xinput set-prop "Microsoft Surface 045E:09AF Touchpad" "libinput Tapping Enabled" 1

picom --experimental-backend -b
statusbar &
sxhkd &

exec dwm
